<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-LOFBR5SJ" failures="1" tests="3" name="runner.TestRunner" time="7.706" errors="0" timestamp="25 Feb 2024 13:09:51 GMT" skipped="0">
  <testcase classname="runner.TestRunner" name="runScenario" time="1.752"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="4.294"/>
  <testcase classname="runner.TestRunner" name="runScenario" time="1.660">
    <failure message="expected [300] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [300] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at stepDefinition.ApiTestingStepDef.i_verify_the_status_code_as(ApiTestingStepDef.java:91)
at âœ½.I verify the status code as "300"(file:src/test/resources/features/APITesting_GetOrder.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
